version: 0.0
os: linux
files:
  - source: /
    destination: /srv/nodejs

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: /srv/nodejs/deploy/ApplicationStop.sh
      timeout: 10
      runas: ec2-user

  AfterInstall:
    - location: /srv/nodejs/deploy/AfterInstall.sh
      timeout: 1200
      runas: ec2-user

  ApplicationStart:
    - location: /srv/nodejs/deploy/ApplicationStart.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: /srv/nodejs/deploy/ValidateService.sh
      timeout: 10
      runas: ec2-user
