version: 0.0
os: linux
files:
  - source: /
    destination: /srv/nodejs

hooks:
  ApplicationStop:
    - location: deploy/ApplicationStop.sh
      timeout: 10

  AfterInstall:
    - location: deploy/AfterInstall.sh
      timeout: 1200

  ApplicationStart:
    - location: deploy/ApplicationStart.sh
      timeout: 60

  ValidateService:
    - location: deploy/ValidateService.sh
      timeout: 10
